### ISSUE TITLE
Button Interrupts

### ISSUE THREAD

**Issue by jennaluz** [jennaluz/SensorMotor#4]
## Get Comfortable
- [x] Create a button interrupt that gives a certain semaphore based on the pushed button
- [x] Debounce button
- [x] Count button input

## Button 1 ISR
- [x] **1 push**: Move stepper motor on temperature #2, #3 
- [x] **2 pushes**: Move stepper motor on humidity #2, #3
- [x] **3 pushes**: Toggle 7 segment display between decimal and hexadecimal #1, #2
- [x] **4 pushes**: Trigger emergency stop #1

## Button 2 ISR
- [x] **1 push**: Continuously move stepper motor clockwise #3
- [x] **2 pushes**: Continuously move stepper motor counterclockwise #3
- [x] **3 pushes**: Alternate stepper motor between clockwise and counterclockwise revolutions #3

## Button 3 ISR
- [x] **1 push**: Display temperature on 7 segment display #1, #2
- [x] **2 pushes**: Display relative humidity on 7 segment display #1, #2
- [x] **3 pushes**: Display stepper motor status on 7 segment display #1, #3

**Comment by jennaluz** [comment]
Implement motor status on display (80d7d104aff669633ec5e697a83bfb86b98d3f52)
